# Generated by Django 6.0.7 on 2026-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_release_playlist_comment_track_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
