# Generated by Django 6.0.7 on 2026-07-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_track_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='audio_file',
        ),
        migrations.AlterField(
            model_name='release',
            name='cover_art',
            field=models.ImageField(blank=True, help_text='3000x3000 pixels recommended. JPG or PNG format.', null=True, upload_to='release_covers/'),
        ),
        migrations.AlterField(
            model_name='release',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='track_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, help_text='MP3, WAV, or FLAC format', null=True, upload_to='tracks/audio/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.CharField(blank=True, help_text='MM:SS format', max_length=20, null=True),
        ),
    ]
