# Generated by Django 5.2.17 on 2026-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_ad_id_alter_adminrequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playhistory',
            name='stream_counted',
            field=models.BooleanField(default=False),
        ),
    ]
